package embed

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"math"
	"time"

	"github.com/spf13/cobra"
	"tiktok-whisper/internal/app/embedding/orchestrator"
	"tiktok-whisper/internal/app/embedding/provider"
	"tiktok-whisper/internal/app/repository/pg"
	"tiktok-whisper/internal/app/storage/vector"
	"tiktok-whisper/internal/config"
)

var Cmd = &cobra.Command{
	Use:   "embed",
	Short: "Manage transcription embeddings",
	Long:  "Generate, manage, and analyze embeddings for transcriptions using OpenAI and Gemini",
}

var generateCmd = &cobra.Command{
	Use:   "generate",
	Short: "Generate embeddings for transcriptions",
	Long: `Generate embeddings for transcriptions using OpenAI and/or Gemini providers.
	
Examples:
  v2t embed generate --all                    # Generate embeddings for all transcriptions
  v2t embed generate --user "用户名"          # Generate for specific user
  v2t embed generate --id 123                # Generate for specific transcription ID
  v2t embed generate --id 123 --force        # Force regenerate embeddings for ID 123
  v2t embed generate --batch-size 5          # Use custom batch size
  v2t embed generate --provider openai       # Use only OpenAI provider
  v2t embed generate --provider gemini       # Use only Gemini provider`,
	Run: runEmbedGenerate,
}

var statusCmd = &cobra.Command{
	Use:   "status",
	Short: "Show embedding generation status",
	Long:  "Display the current status of embedding generation for transcriptions",
	Run:   runEmbedStatus,
}

var testCmd = &cobra.Command{
	Use:   "test",
	Short: "Test embedding retrieval and verification",
	Long:  "Test retrieval of generated embeddings and verify vector dimensions",
	Run:   runEmbedTest,
}

var similarityCmd = &cobra.Command{
	Use:   "similarity",
	Short: "Calculate similarity between transcriptions",
	Long:  "Calculate cosine similarity between embeddings of different transcriptions",
	Run:   runEmbedSimilarity,
}

var searchCmd = &cobra.Command{
	Use:   "search",
	Short: "Search for similar transcriptions using vector similarity",
	Long:  "Search for transcriptions similar to a given ID or text using pgvector database similarity search",
	Run:   runEmbedSearch,
}

var duplicatesCmd = &cobra.Command{
	Use:   "duplicates",
	Short: "Find potential duplicate transcriptions using embedding similarity",
	Long:  "Find pairs of transcriptions with high similarity that may be duplicates",
	Run:   runEmbedDuplicates,
}

var compareCmd = &cobra.Command{
	Use:   "compare",
	Short: "Compare embedding providers for a specific transcription or text",
	Long:  "Compare embeddings generated by different providers to analyze their similarity and differences",
	Run:   runEmbedCompare,
}

// Command flags
var (
	flagAll       bool
	flagUser      string
	flagBatchSize int
	flagProvider  string
	flagID        int
	flagForce     bool
	flagID1       int
	flagID2       int
	flagLimit     int
	flagThreshold float64
	flagText      string
)

func init() {
	// Add subcommands
	Cmd.AddCommand(generateCmd)
	Cmd.AddCommand(statusCmd)
	Cmd.AddCommand(testCmd)
	Cmd.AddCommand(similarityCmd)
	Cmd.AddCommand(searchCmd)
	Cmd.AddCommand(duplicatesCmd)
	Cmd.AddCommand(compareCmd)

	// Generate command flags
	generateCmd.Flags().BoolVar(&flagAll, "all", false, "Generate embeddings for all transcriptions")
	generateCmd.Flags().StringVar(&flagUser, "user", "", "Generate embeddings for specific user")
	generateCmd.Flags().IntVar(&flagID, "id", 0, "Generate embeddings for specific transcription ID")
	generateCmd.Flags().BoolVar(&flagForce, "force", false, "Force regenerate embeddings even if they already exist")
	generateCmd.Flags().IntVar(&flagBatchSize, "batch-size", 10, "Number of transcriptions to process in each batch")
	generateCmd.Flags().StringVar(&flagProvider, "provider", "both", "Provider to use (openai, gemini, both)")

	// Similarity command flags
	similarityCmd.Flags().IntVar(&flagID1, "id1", 0, "First transcription ID for similarity comparison")
	similarityCmd.Flags().IntVar(&flagID2, "id2", 0, "Second transcription ID for similarity comparison")
	similarityCmd.Flags().StringVar(&flagProvider, "provider", "gemini", "Provider to use for similarity (openai, gemini)")
	similarityCmd.MarkFlagRequired("id1")
	similarityCmd.MarkFlagRequired("id2")

	// Search command flags
	searchCmd.Flags().IntVar(&flagID, "id", 0, "Transcription ID to search for similar content")
	searchCmd.Flags().StringVar(&flagText, "text", "", "Text content to search for similar transcriptions")
	searchCmd.Flags().StringVar(&flagProvider, "provider", "gemini", "Provider to use for search (openai, gemini)")
	searchCmd.Flags().IntVar(&flagLimit, "limit", 10, "Maximum number of similar results to return")
	searchCmd.Flags().Float64Var(&flagThreshold, "threshold", 0.5, "Minimum similarity threshold (0.0-1.0)")

	// Duplicates command flags
	duplicatesCmd.Flags().StringVar(&flagProvider, "provider", "gemini", "Provider to use for duplicate detection (openai, gemini)")
	duplicatesCmd.Flags().Float64Var(&flagThreshold, "threshold", 0.95, "Minimum similarity threshold for considering duplicates (0.0-1.0)")
	duplicatesCmd.Flags().IntVar(&flagLimit, "limit", 100, "Maximum number of duplicate pairs to return")
	duplicatesCmd.Flags().StringVar(&flagUser, "user", "", "Limit search to specific user")

	// Compare command flags
	compareCmd.Flags().IntVar(&flagID, "id", 0, "Transcription ID to compare providers for")
	compareCmd.Flags().StringVar(&flagText, "text", "", "Text to compare providers for")
}

func runEmbedGenerate(cmd *cobra.Command, args []string) {
	// Load and validate API keys for embedding operations (fail-fast)
	apiKeys, err := config.GetAPIKeys()
	if err != nil {
		log.Fatalf("❌ Failed to load API keys: %v", err)
	}

	// Show API key status for embedding operations
	config.ShowAPIKeyStatus(apiKeys)

	// Require at least one API key for embedding operations
	if err := config.RequireAPIKeys(apiKeys); err != nil {
		log.Fatalf("❌ %v", err)
	}

	// Initialize database
	db, err := pg.GetConnection()
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	// Test database connection
	if err := db.Ping(); err != nil {
		log.Fatalf("Failed to ping database: %v", err)
	}

	// Create providers based on flag and available API keys
	providers := make(map[string]provider.EmbeddingProvider)

	if flagProvider == "openai" || flagProvider == "both" {
		if apiKeys.OpenAI != "" {
			providers["openai"] = provider.NewOpenAIProvider(apiKeys.OpenAI)
			fmt.Println("✅ Using OpenAI provider for embeddings")
		} else if flagProvider == "openai" {
			log.Fatalf("❌ OpenAI provider requested but OPENAI_API_KEY not available")
		}
	}

	if flagProvider == "gemini" || flagProvider == "both" {
		if apiKeys.Gemini != "" {
			providers["gemini"] = provider.NewGeminiProvider(apiKeys.Gemini)
			fmt.Println("✅ Using Gemini provider for embeddings")
		} else if flagProvider == "gemini" {
			log.Fatalf("❌ Gemini provider requested but GEMINI_API_KEY not available")
		}
	}

	if len(providers) == 0 {
		log.Fatalf("❌ No embedding providers available for the requested configuration")
	}

	// Create storage and orchestrator
	storage := vector.NewPgVectorStorage(db)
	defer storage.Close()

	logger := &SimpleLogger{}
	embedOrchestrator := orchestrator.NewEmbeddingOrchestrator(providers, storage, logger)

	// Create batch processor
	processor := orchestrator.NewBatchProcessor(embedOrchestrator, storage, logger)

	ctx := context.Background()

	if flagAll {
		fmt.Println("Generating embeddings for all transcriptions...")
		// Determine which providers to process based on what's configured
		var providerNames []string
		for providerName := range providers {
			providerNames = append(providerNames, providerName)
		}
		err = processor.ProcessAllTranscriptions(ctx, providerNames, flagBatchSize)
	} else if flagUser != "" {
		fmt.Printf("Generating embeddings for user: %s\n", flagUser)

		// Determine which providers to process based on what's configured
		var providerNames []string
		for providerName := range providers {
			providerNames = append(providerNames, providerName)
		}

		if len(providerNames) == 0 {
			log.Fatalf("❌ No providers available. Please check your API key configuration.")
		}

		fmt.Printf("📊 Using providers: %v\n", providerNames)

		// Get user statistics before processing
		userStats, err := storage.GetUserEmbeddingStats(ctx, flagUser)
		if err != nil {
			log.Printf("⚠️  Unable to get user statistics: %v", err)
		} else {
			fmt.Printf("📈 User Statistics - Total: %d, OpenAI: %d, Gemini: %d, Pending OpenAI: %d, Pending Gemini: %d\n",
				userStats.TotalTranscriptions, userStats.OpenAIEmbeddings, userStats.GeminiEmbeddings,
				userStats.PendingOpenAI, userStats.PendingGemini)
		}

		// Process user-specific transcriptions
		err = processor.ProcessUserTranscriptions(ctx, flagUser, providerNames, flagBatchSize)
		if err != nil {
			log.Fatalf("❌ Error generating user-specific embeddings: %v", err)
		}

		fmt.Printf("✅ Successfully generated embeddings for user: %s\n", flagUser)
	} else if flagID > 0 {
		fmt.Printf("Generating embeddings for transcription ID: %d\n", flagID)
		err = processSingleTranscription(ctx, embedOrchestrator, storage, flagID, flagProvider, flagForce)
	} else {
		cmd.Help()
		return
	}

	if err != nil {
		log.Fatalf("Error generating embeddings: %v", err)
	}

	fmt.Println("Embedding generation completed successfully!")
}

func runEmbedStatus(cmd *cobra.Command, args []string) {
	// Initialize database
	db, err := pg.GetConnection()
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	// Test database connection
	if err := db.Ping(); err != nil {
		log.Fatalf("Failed to ping database: %v", err)
	}

	// Query embedding status
	ctx := context.Background()

	// Count total transcriptions
	var totalCount int
	err = db.QueryRowContext(ctx, "SELECT COUNT(*) FROM transcriptions").Scan(&totalCount)
	if err != nil {
		log.Fatalf("Failed to get total count: %v", err)
	}

	// Count embeddings by provider
	var openaiCount, geminiCount int
	err = db.QueryRowContext(ctx, "SELECT COUNT(*) FROM transcriptions WHERE embedding_openai IS NOT NULL").Scan(&openaiCount)
	if err != nil {
		log.Fatalf("Failed to get OpenAI count: %v", err)
	}

	err = db.QueryRowContext(ctx, "SELECT COUNT(*) FROM transcriptions WHERE embedding_gemini IS NOT NULL").Scan(&geminiCount)
	if err != nil {
		log.Fatalf("Failed to get Gemini count: %v", err)
	}

	// Display status
	fmt.Printf("Embedding Status:\n")
	fmt.Printf("  Total transcriptions: %d\n", totalCount)
	fmt.Printf("  OpenAI embeddings: %d (%.1f%%)\n", openaiCount, float64(openaiCount)/float64(totalCount)*100)
	fmt.Printf("  Gemini embeddings: %d (%.1f%%)\n", geminiCount, float64(geminiCount)/float64(totalCount)*100)

	// Count pending
	var pendingCount int
	err = db.QueryRowContext(ctx, "SELECT COUNT(*) FROM transcriptions WHERE embedding_openai IS NULL OR embedding_gemini IS NULL").Scan(&pendingCount)
	if err == nil {
		fmt.Printf("  Pending processing: %d\n", pendingCount)
	}

	// Show user distribution
	fmt.Printf("\nUser Distribution (Top 10):\n")
	userQuery := `SELECT user_nickname, COUNT(*) as count, 
				  COUNT(CASE WHEN embedding_gemini IS NOT NULL THEN 1 END) as gemini_count,
				  COUNT(CASE WHEN embedding_openai IS NOT NULL THEN 1 END) as openai_count
				  FROM transcriptions 
				  GROUP BY user_nickname 
				  ORDER BY count DESC 
				  LIMIT 10`

	rows, err := db.QueryContext(ctx, userQuery)
	if err == nil {
		defer rows.Close()
		for rows.Next() {
			var user string
			var count, geminiCount, openaiCount int
			if err := rows.Scan(&user, &count, &geminiCount, &openaiCount); err == nil {
				fmt.Printf("  %s: %d transcriptions (%d Gemini, %d OpenAI)\n", user, count, geminiCount, openaiCount)
			}
		}
	}

	// Show sample embedding data format
	fmt.Printf("\nSample Embedding Data:\n")
	sampleQuery := `SELECT id, user_nickname, 
					CASE WHEN embedding_gemini IS NOT NULL THEN 'Gemini: ' || array_length(embedding_gemini, 1) || 'D' ELSE 'No Gemini' END as gemini_info,
					CASE WHEN embedding_openai IS NOT NULL THEN 'OpenAI: ' || array_length(embedding_openai, 1) || 'D' ELSE 'No OpenAI' END as openai_info
					FROM transcriptions 
					WHERE embedding_gemini IS NOT NULL OR embedding_openai IS NOT NULL 
					ORDER BY id 
					LIMIT 5`

	sampleRows, err := db.QueryContext(ctx, sampleQuery)
	if err == nil {
		defer sampleRows.Close()
		for sampleRows.Next() {
			var id int
			var user, geminiInfo, openaiInfo string
			if err := sampleRows.Scan(&id, &user, &geminiInfo, &openaiInfo); err == nil {
				fmt.Printf("  ID %d (%s): %s, %s\n", id, user, geminiInfo, openaiInfo)
			}
		}
	}
}

// SimpleLogger implements the Logger interface
type SimpleLogger struct{}

func (l *SimpleLogger) Info(msg string, keysAndValues ...interface{}) {
	fmt.Printf("INFO: %s", msg)
	for i := 0; i < len(keysAndValues); i += 2 {
		if i+1 < len(keysAndValues) {
			fmt.Printf(" %v=%v", keysAndValues[i], keysAndValues[i+1])
		}
	}
	fmt.Println()
}

func (l *SimpleLogger) Error(msg string, keysAndValues ...interface{}) {
	fmt.Printf("ERROR: %s", msg)
	for i := 0; i < len(keysAndValues); i += 2 {
		if i+1 < len(keysAndValues) {
			fmt.Printf(" %v=%v", keysAndValues[i], keysAndValues[i+1])
		}
	}
	fmt.Println()
}

// processSingleTranscription processes embedding generation for a single transcription by ID
func processSingleTranscription(ctx context.Context, embedOrchestrator *orchestrator.EmbeddingOrchestrator, storage *vector.PgVectorStorage, id int, provider string, force bool) error {
	// Since we need to query the database, let's create a direct connection
	// This is a simplified approach for single record processing
	db, err := pg.GetConnection()
	if err != nil {
		return fmt.Errorf("failed to connect to database: %w", err)
	}
	defer db.Close()

	// Query the transcription by ID
	query := `SELECT id, transcription, user_nickname FROM transcriptions WHERE id = $1`
	row := db.QueryRowContext(ctx, query, id)

	var transcriptionID int
	var text, userNickname string

	err = row.Scan(&transcriptionID, &text, &userNickname)
	if err != nil {
		if err == sql.ErrNoRows {
			return fmt.Errorf("transcription with ID %d not found", id)
		}
		return fmt.Errorf("error querying transcription: %w", err)
	}

	fmt.Printf("Found transcription ID %d (user: %s)\n", transcriptionID, userNickname)
	fmt.Printf("Text preview: %.100s...\n", text)

	// Check if embeddings already exist (unless force is specified)
	if !force {
		needsGeneration := false

		if provider == "openai" || provider == "both" {
			_, err := storage.GetEmbedding(ctx, transcriptionID, "openai")
			if err != nil {
				needsGeneration = true
				fmt.Println("  → OpenAI embedding missing, will generate")
			} else {
				fmt.Println("  ✓ OpenAI embedding already exists, skipping")
			}
		}

		if provider == "gemini" || provider == "both" {
			_, err := storage.GetEmbedding(ctx, transcriptionID, "gemini")
			if err != nil {
				needsGeneration = true
				fmt.Println("  → Gemini embedding missing, will generate")
			} else {
				fmt.Println("  ✓ Gemini embedding already exists, skipping")
			}
		}

		if !needsGeneration {
			fmt.Printf("✅ All required embeddings already exist for transcription ID %d (use --force to regenerate)\n", transcriptionID)
			return nil
		}
	} else {
		fmt.Println("  🔄 Force mode enabled, will regenerate all embeddings")
	}

	// Use the orchestrator to process this single transcription
	err = embedOrchestrator.ProcessTranscription(ctx, transcriptionID, text)
	if err != nil {
		return fmt.Errorf("error processing transcription: %w", err)
	}

	fmt.Printf("✅ Successfully generated and stored embeddings for transcription ID %d\n", transcriptionID)
	return nil
}

func runEmbedTest(cmd *cobra.Command, args []string) {
	// Initialize database
	db, err := pg.GetConnection()
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	// Test database connection
	if err := db.Ping(); err != nil {
		log.Fatalf("Failed to ping database: %v", err)
	}

	// Create storage
	storage := vector.NewPgVectorStorage(db)
	defer storage.Close()

	ctx := context.Background()

	// Test IDs that we know have embeddings
	testIDs := []int{2, 3}

	fmt.Println("Testing embedding retrieval and verification...")
	fmt.Println()

	for _, id := range testIDs {
		fmt.Printf("Testing transcription ID: %d\n", id)

		// Test Gemini embedding
		geminiEmbedding, err := storage.GetEmbedding(ctx, id, "gemini")
		if err != nil {
			fmt.Printf("  ❌ Failed to get Gemini embedding: %v\n", err)
		} else {
			fmt.Printf("  ✅ Gemini embedding: %d dimensions\n", len(geminiEmbedding))
			if len(geminiEmbedding) > 0 {
				fmt.Printf("      First 5 values: %.6f, %.6f, %.6f, %.6f, %.6f\n",
					geminiEmbedding[0], geminiEmbedding[1], geminiEmbedding[2],
					geminiEmbedding[3], geminiEmbedding[4])
			}
		}

		// Test OpenAI embedding (may not exist)
		openaiEmbedding, err := storage.GetEmbedding(ctx, id, "openai")
		if err != nil {
			fmt.Printf("  ❌ No OpenAI embedding found (expected): %v\n", err)
		} else {
			fmt.Printf("  ✅ OpenAI embedding: %d dimensions\n", len(openaiEmbedding))
		}

		fmt.Println()
	}

	fmt.Println("Embedding test completed!")
}

func runEmbedSimilarity(cmd *cobra.Command, args []string) {
	// Initialize database
	db, err := pg.GetConnection()
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	// Test database connection
	if err := db.Ping(); err != nil {
		log.Fatalf("Failed to ping database: %v", err)
	}

	// Create storage
	storage := vector.NewPgVectorStorage(db)
	defer storage.Close()

	ctx := context.Background()

	fmt.Printf("Calculating similarity between transcription ID %d and ID %d using %s embeddings...\n\n", flagID1, flagID2, flagProvider)

	// Get embeddings for both IDs
	embedding1, err := storage.GetEmbedding(ctx, flagID1, flagProvider)
	if err != nil {
		log.Fatalf("Failed to get %s embedding for ID %d: %v", flagProvider, flagID1, err)
	}

	embedding2, err := storage.GetEmbedding(ctx, flagID2, flagProvider)
	if err != nil {
		log.Fatalf("Failed to get %s embedding for ID %d: %v", flagProvider, flagID2, err)
	}

	// Get transcription texts for context
	text1, user1, err := getTranscriptionInfo(db, ctx, flagID1)
	if err != nil {
		log.Fatalf("Failed to get transcription info for ID %d: %v", flagID1, err)
	}

	text2, user2, err := getTranscriptionInfo(db, ctx, flagID2)
	if err != nil {
		log.Fatalf("Failed to get transcription info for ID %d: %v", flagID2, err)
	}

	// Calculate cosine similarity
	similarity := cosineSimilarity(embedding1, embedding2)

	// Display results
	fmt.Printf("📊 Similarity Analysis Results:\n")
	fmt.Printf("   Provider: %s (%d dimensions)\n", flagProvider, len(embedding1))
	fmt.Printf("   Cosine Similarity: %.6f\n\n", similarity)

	// Interpret similarity score
	var interpretation string
	switch {
	case similarity >= 0.9:
		interpretation = "Very High Similarity - Nearly identical content"
	case similarity >= 0.8:
		interpretation = "High Similarity - Very related content"
	case similarity >= 0.7:
		interpretation = "Good Similarity - Related content"
	case similarity >= 0.5:
		interpretation = "Moderate Similarity - Some relation"
	case similarity >= 0.3:
		interpretation = "Low Similarity - Little relation"
	default:
		interpretation = "Very Low Similarity - Unrelated content"
	}

	fmt.Printf("🎯 Interpretation: %s\n\n", interpretation)

	// Show transcription details
	fmt.Printf("📝 Transcription Details:\n")
	fmt.Printf("   ID %d (User: %s):\n      %s\n\n", flagID1, user1, truncateText(text1, 150))
	fmt.Printf("   ID %d (User: %s):\n      %s\n\n", flagID2, user2, truncateText(text2, 150))

	fmt.Println("Similarity calculation completed!")
}

// cosineSimilarity calculates the cosine similarity between two vectors
func cosineSimilarity(a, b []float32) float64 {
	if len(a) != len(b) {
		return 0.0
	}

	var dotProduct, normA, normB float64

	for i := 0; i < len(a); i++ {
		dotProduct += float64(a[i]) * float64(b[i])
		normA += float64(a[i]) * float64(a[i])
		normB += float64(b[i]) * float64(b[i])
	}

	if normA == 0.0 || normB == 0.0 {
		return 0.0
	}

	return dotProduct / (math.Sqrt(normA) * math.Sqrt(normB))
}

// getTranscriptionInfo retrieves transcription text and user info
func getTranscriptionInfo(db *sql.DB, ctx context.Context, id int) (string, string, error) {
	query := `SELECT transcription, user_nickname FROM transcriptions WHERE id = $1`

	var text, user string
	err := db.QueryRowContext(ctx, query, id).Scan(&text, &user)
	if err != nil {
		return "", "", err
	}

	return text, user, nil
}

// truncateText truncates text to specified length with ellipsis
func truncateText(text string, maxLen int) string {
	if len(text) <= maxLen {
		return text
	}
	return text[:maxLen] + "..."
}

func runEmbedSearch(cmd *cobra.Command, args []string) {
	// Validate input: either ID or text must be provided
	if flagID == 0 && flagText == "" {
		log.Fatalf("❌ Either --id or --text must be provided")
	}
	if flagID != 0 && flagText != "" {
		log.Fatalf("❌ Please provide either --id or --text, not both")
	}

	// Initialize database
	db, err := pg.GetConnection()
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	// Test database connection
	if err := db.Ping(); err != nil {
		log.Fatalf("Failed to ping database: %v", err)
	}

	// Create storage
	storage := vector.NewPgVectorStorage(db)
	defer storage.Close()

	ctx := context.Background()

	var targetEmbedding []float32
	var excludeID int

	if flagText != "" {
		// Text search mode - generate embedding for the input text
		fmt.Printf("🔍 Searching for transcriptions similar to input text using %s embeddings...\n\n", flagProvider)

		// Load and validate API keys for real-time embedding generation
		apiKeys, err := config.GetAPIKeys()
		if err != nil {
			log.Fatalf("❌ Failed to load API keys: %v", err)
		}

		if err := config.RequireAPIKeys(apiKeys); err != nil {
			log.Fatalf("❌ %v", err)
		}

		// Generate embedding for the input text
		fmt.Println("🔄 Generating embedding for input text...")
		targetEmbedding, err = generateTextEmbedding(ctx, flagText, flagProvider, apiKeys)
		if err != nil {
			log.Fatalf("Failed to generate embedding for input text: %v", err)
		}

		fmt.Printf("📝 Input Text:\n   %s\n\n", truncateText(flagText, 200))
		excludeID = -1 // No ID to exclude

	} else {
		// ID search mode - get existing embedding
		fmt.Printf("🔍 Searching for transcriptions similar to ID %d using %s embeddings...\n\n", flagID, flagProvider)

		// Get the target embedding
		targetEmbedding, err = storage.GetEmbedding(ctx, flagID, flagProvider)
		if err != nil {
			log.Fatalf("Failed to get %s embedding for ID %d: %v", flagProvider, flagID, err)
		}

		// Get target transcription info for context
		targetText, targetUser, err := getTranscriptionInfo(db, ctx, flagID)
		if err != nil {
			log.Fatalf("Failed to get transcription info for ID %d: %v", flagID, err)
		}

		fmt.Printf("📝 Target Transcription (ID %d):\n", flagID)
		fmt.Printf("   User: %s\n", targetUser)
		fmt.Printf("   Text: %s\n\n", truncateText(targetText, 200))
		excludeID = flagID
	}

	// Perform vector similarity search using pgvector
	results, err := performVectorSearch(db, ctx, targetEmbedding, flagProvider, excludeID, flagLimit, flagThreshold)
	if err != nil {
		log.Fatalf("Failed to perform vector search: %v", err)
	}

	// Display results
	if len(results) == 0 {
		fmt.Printf("❌ No similar transcriptions found with similarity >= %.3f\n", flagThreshold)
		fmt.Printf("💡 Try lowering the --threshold value or increasing --limit\n")
		return
	}

	fmt.Printf("✅ Found %d similar transcriptions:\n\n", len(results))

	for i, result := range results {
		fmt.Printf("%d. 📄 ID %d (Similarity: %.6f)\n", i+1, result.ID, result.Similarity)
		fmt.Printf("   👤 User: %s\n", result.User)
		fmt.Printf("   📝 Text: %s\n", truncateText(result.Text, 180))

		// Add interpretation
		var interpretation string
		switch {
		case result.Similarity >= 0.9:
			interpretation = "Very High"
		case result.Similarity >= 0.8:
			interpretation = "High"
		case result.Similarity >= 0.7:
			interpretation = "Good"
		case result.Similarity >= 0.5:
			interpretation = "Moderate"
		default:
			interpretation = "Low"
		}
		fmt.Printf("   🎯 Similarity: %s\n\n", interpretation)
	}

	fmt.Printf("Search completed! Found %d results above threshold %.3f\n", len(results), flagThreshold)
}

// SearchResult represents a search result with similarity score
type SearchResult struct {
	ID         int
	Text       string
	User       string
	Similarity float64
}

// performVectorSearch executes pgvector similarity search
func performVectorSearch(db *sql.DB, ctx context.Context, targetEmbedding []float32, provider string, excludeID, limit int, threshold float64) ([]SearchResult, error) {
	// Convert embedding to pgvector format
	embeddingStr := vectorToString(targetEmbedding)

	// Build query based on provider
	var embeddingColumn string
	switch provider {
	case "openai":
		embeddingColumn = "embedding_openai"
	case "gemini":
		embeddingColumn = "embedding_gemini"
	default:
		return nil, fmt.Errorf("unsupported provider: %s", provider)
	}

	// Use pgvector cosine distance operator <=> for similarity search
	// Note: cosine distance = 1 - cosine similarity, so we need to convert
	query := fmt.Sprintf(`
		SELECT 
			id, 
			transcription, 
			user_nickname,
			1 - (%s <=> $1) as similarity
		FROM transcriptions 
		WHERE id != $2 
			AND %s IS NOT NULL
			AND 1 - (%s <=> $1) >= $3
		ORDER BY %s <=> $1
		LIMIT $4
	`, embeddingColumn, embeddingColumn, embeddingColumn, embeddingColumn)

	rows, err := db.QueryContext(ctx, query, embeddingStr, excludeID, threshold, limit)
	if err != nil {
		return nil, fmt.Errorf("failed to execute vector search query: %w", err)
	}
	defer rows.Close()

	var results []SearchResult
	for rows.Next() {
		var result SearchResult
		err := rows.Scan(&result.ID, &result.Text, &result.User, &result.Similarity)
		if err != nil {
			return nil, fmt.Errorf("failed to scan search result: %w", err)
		}
		results = append(results, result)
	}

	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating search results: %w", err)
	}

	return results, nil
}

// vectorToString converts float32 slice to pgvector string format
func vectorToString(embedding []float32) string {
	if len(embedding) == 0 {
		return "[]"
	}

	result := "["
	for i, val := range embedding {
		if i > 0 {
			result += ","
		}
		result += fmt.Sprintf("%.9f", val)
	}
	result += "]"
	return result
}

// generateTextEmbedding generates an embedding for input text using the specified provider
func generateTextEmbedding(ctx context.Context, text, providerName string, apiKeys *config.APIKeys) ([]float32, error) {
	var embeddingProvider provider.EmbeddingProvider

	switch providerName {
	case "openai":
		if apiKeys.OpenAI == "" {
			return nil, fmt.Errorf("OpenAI API key not available")
		}
		embeddingProvider = provider.NewOpenAIProvider(apiKeys.OpenAI)
	case "gemini":
		if apiKeys.Gemini == "" {
			return nil, fmt.Errorf("Gemini API key not available")
		}
		embeddingProvider = provider.NewGeminiProvider(apiKeys.Gemini)
	default:
		return nil, fmt.Errorf("unsupported provider: %s", providerName)
	}

	// Generate embedding
	embedding, err := embeddingProvider.GenerateEmbedding(ctx, text)
	if err != nil {
		return nil, fmt.Errorf("failed to generate %s embedding: %w", providerName, err)
	}

	fmt.Printf("✅ Generated %s embedding (%d dimensions)\n", providerName, len(embedding))
	return embedding, nil
}

func runEmbedDuplicates(cmd *cobra.Command, args []string) {
	// Initialize database
	db, err := pg.GetConnection()
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	// Test database connection
	if err := db.Ping(); err != nil {
		log.Fatalf("Failed to ping database: %v", err)
	}

	ctx := context.Background()

	fmt.Printf("🔍 Finding potential duplicates using %s embeddings (threshold: %.3f)...\n\n", flagProvider, flagThreshold)

	// Find duplicate pairs
	duplicatePairs, err := findDuplicatePairs(db, ctx, flagProvider, flagThreshold, flagLimit, flagUser)
	if err != nil {
		log.Fatalf("Failed to find duplicate pairs: %v", err)
	}

	if len(duplicatePairs) == 0 {
		fmt.Printf("✅ No potential duplicates found with similarity >= %.3f\n", flagThreshold)
		fmt.Printf("💡 Try lowering the --threshold value if you expect duplicates\n")
		return
	}

	fmt.Printf("⚠️  Found %d potential duplicate pairs:\n\n", len(duplicatePairs))

	for i, pair := range duplicatePairs {
		fmt.Printf("%d. 🔄 Potential Duplicate (Similarity: %.6f)\n", i+1, pair.Similarity)
		fmt.Printf("   📄 ID %d (User: %s): %s\n", pair.ID1, pair.User1, truncateText(pair.Text1, 120))
		fmt.Printf("   📄 ID %d (User: %s): %s\n", pair.ID2, pair.User2, truncateText(pair.Text2, 120))

		// Add severity interpretation
		var severity string
		switch {
		case pair.Similarity >= 0.98:
			severity = "🔴 Very High - Almost identical"
		case pair.Similarity >= 0.95:
			severity = "🟠 High - Likely duplicate"
		case pair.Similarity >= 0.90:
			severity = "🟡 Medium - Possible duplicate"
		default:
			severity = "🔵 Low - Similar content"
		}
		fmt.Printf("   %s\n\n", severity)
	}

	fmt.Printf("Summary: Found %d duplicate pairs above threshold %.3f\n", len(duplicatePairs), flagThreshold)
	if len(duplicatePairs) >= flagLimit {
		fmt.Printf("💡 Results limited to %d pairs. Use --limit to see more.\n", flagLimit)
	}
}

// DuplicatePair represents a pair of similar transcriptions
type DuplicatePair struct {
	ID1        int
	ID2        int
	Text1      string
	Text2      string
	User1      string
	User2      string
	Similarity float64
}

// findDuplicatePairs finds pairs of transcriptions with high similarity
func findDuplicatePairs(db *sql.DB, ctx context.Context, provider string, threshold float64, limit int, user string) ([]DuplicatePair, error) {
	// Choose embedding column based on provider
	var embeddingColumn string
	switch provider {
	case "openai":
		embeddingColumn = "embedding_openai"
	case "gemini":
		embeddingColumn = "embedding_gemini"
	default:
		return nil, fmt.Errorf("unsupported provider: %s", provider)
	}

	// Build query for finding similar pairs
	var query string
	var args []interface{}

	if user != "" {
		// User-specific search
		query = fmt.Sprintf(`
			SELECT 
				t1.id, t2.id,
				t1.transcription, t2.transcription,
				t1.user_nickname, t2.user_nickname,
				1 - (t1.%s <=> t2.%s) as similarity
			FROM transcriptions t1
			CROSS JOIN transcriptions t2
			WHERE t1.id < t2.id
				AND t1.%s IS NOT NULL 
				AND t2.%s IS NOT NULL
				AND (t1.user_nickname = $1 OR t2.user_nickname = $1)
				AND 1 - (t1.%s <=> t2.%s) >= $2
			ORDER BY similarity DESC
			LIMIT $3
		`, embeddingColumn, embeddingColumn, embeddingColumn, embeddingColumn, embeddingColumn, embeddingColumn)
		args = []interface{}{user, threshold, limit}
	} else {
		// Global search
		query = fmt.Sprintf(`
			SELECT 
				t1.id, t2.id,
				t1.transcription, t2.transcription,
				t1.user_nickname, t2.user_nickname,
				1 - (t1.%s <=> t2.%s) as similarity
			FROM transcriptions t1
			CROSS JOIN transcriptions t2
			WHERE t1.id < t2.id
				AND t1.%s IS NOT NULL 
				AND t2.%s IS NOT NULL
				AND 1 - (t1.%s <=> t2.%s) >= $1
			ORDER BY similarity DESC
			LIMIT $2
		`, embeddingColumn, embeddingColumn, embeddingColumn, embeddingColumn, embeddingColumn, embeddingColumn)
		args = []interface{}{threshold, limit}
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to execute duplicate search query: %w", err)
	}
	defer rows.Close()

	var pairs []DuplicatePair
	for rows.Next() {
		var pair DuplicatePair
		err := rows.Scan(
			&pair.ID1, &pair.ID2,
			&pair.Text1, &pair.Text2,
			&pair.User1, &pair.User2,
			&pair.Similarity,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan duplicate pair: %w", err)
		}
		pairs = append(pairs, pair)
	}

	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating duplicate pairs: %w", err)
	}

	return pairs, nil
}

func runEmbedCompare(cmd *cobra.Command, args []string) {
	// Validate input: either ID or text must be provided
	if flagID == 0 && flagText == "" {
		log.Fatalf("❌ Either --id or --text must be provided")
	}
	if flagID != 0 && flagText != "" {
		log.Fatalf("❌ Please provide either --id or --text, not both")
	}

	// Load and validate API keys for embedding operations
	apiKeys, err := config.GetAPIKeys()
	if err != nil {
		log.Fatalf("❌ Failed to load API keys: %v", err)
	}

	// Initialize database
	db, err := pg.GetConnection()
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	// Test database connection
	if err := db.Ping(); err != nil {
		log.Fatalf("Failed to ping database: %v", err)
	}

	// Create storage
	storage := vector.NewPgVectorStorage(db)
	defer storage.Close()

	ctx := context.Background()
	var targetText string

	if flagText != "" {
		// Text comparison mode
		targetText = flagText
		fmt.Printf("🔍 Comparing embedding providers for input text...\n\n")
		fmt.Printf("📝 Input Text:\n   %s\n\n", truncateText(targetText, 200))
	} else {
		// ID comparison mode
		fmt.Printf("🔍 Comparing embedding providers for transcription ID %d...\n\n", flagID)

		// Get transcription text
		var user string
		targetText, user, err = getTranscriptionInfo(db, ctx, flagID)
		if err != nil {
			log.Fatalf("Failed to get transcription info for ID %d: %v", flagID, err)
		}

		fmt.Printf("📝 Transcription (ID %d):\n", flagID)
		fmt.Printf("   User: %s\n", user)
		fmt.Printf("   Text: %s\n\n", truncateText(targetText, 200))
	}

	// Analyze provider availability and existing embeddings
	providerComparison, err := analyzeProviderEmbeddings(ctx, storage, apiKeys, flagID, targetText)
	if err != nil {
		log.Fatalf("Failed to analyze provider embeddings: %v", err)
	}

	// Display comparison results
	displayProviderComparison(providerComparison)
}

// ProviderComparison holds comparison results between embedding providers
type ProviderComparison struct {
	TargetText      string
	TranscriptionID int
	OpenAIAvailable bool
	GeminiAvailable bool
	OpenAIEmbedding []float32
	GeminiEmbedding []float32
	OpenAIGenerated bool
	GeminiGenerated bool
	CrossSimilarity float64 // Similarity between OpenAI and Gemini embeddings
	Dimensions      map[string]int
	GenerationTime  map[string]string
	Errors          map[string]string
}

// analyzeProviderEmbeddings retrieves or generates embeddings for comparison
func analyzeProviderEmbeddings(ctx context.Context, storage *vector.PgVectorStorage, apiKeys *config.APIKeys, id int, text string) (*ProviderComparison, error) {
	comparison := &ProviderComparison{
		TargetText:      text,
		TranscriptionID: id,
		OpenAIAvailable: apiKeys.OpenAI != "",
		GeminiAvailable: apiKeys.Gemini != "",
		Dimensions:      make(map[string]int),
		GenerationTime:  make(map[string]string),
		Errors:          make(map[string]string),
	}

	// Try to get existing embeddings if ID is provided
	if id > 0 {
		// Try OpenAI embedding
		if comparison.OpenAIAvailable {
			openaiEmbedding, err := storage.GetEmbedding(ctx, id, "openai")
			if err == nil {
				comparison.OpenAIEmbedding = openaiEmbedding
				comparison.Dimensions["openai"] = len(openaiEmbedding)
				comparison.GenerationTime["openai"] = "Retrieved from database"
			} else {
				comparison.Errors["openai"] = "Not found in database"
			}
		}

		// Try Gemini embedding
		if comparison.GeminiAvailable {
			geminiEmbedding, err := storage.GetEmbedding(ctx, id, "gemini")
			if err == nil {
				comparison.GeminiEmbedding = geminiEmbedding
				comparison.Dimensions["gemini"] = len(geminiEmbedding)
				comparison.GenerationTime["gemini"] = "Retrieved from database"
			} else {
				comparison.Errors["gemini"] = "Not found in database"
			}
		}
	}

	// Generate missing embeddings if APIs are available
	if comparison.OpenAIAvailable && comparison.OpenAIEmbedding == nil {
		fmt.Println("🔄 Generating OpenAI embedding...")
		start := time.Now()
		embedding, err := generateTextEmbedding(ctx, text, "openai", apiKeys)
		if err != nil {
			comparison.Errors["openai"] = fmt.Sprintf("Generation failed: %v", err)
		} else {
			comparison.OpenAIEmbedding = embedding
			comparison.OpenAIGenerated = true
			comparison.Dimensions["openai"] = len(embedding)
			comparison.GenerationTime["openai"] = fmt.Sprintf("Generated in %v", time.Since(start).Round(time.Millisecond))
		}
	}

	if comparison.GeminiAvailable && comparison.GeminiEmbedding == nil {
		fmt.Println("🔄 Generating Gemini embedding...")
		start := time.Now()
		embedding, err := generateTextEmbedding(ctx, text, "gemini", apiKeys)
		if err != nil {
			comparison.Errors["gemini"] = fmt.Sprintf("Generation failed: %v", err)
		} else {
			comparison.GeminiEmbedding = embedding
			comparison.GeminiGenerated = true
			comparison.Dimensions["gemini"] = len(embedding)
			comparison.GenerationTime["gemini"] = fmt.Sprintf("Generated in %v", time.Since(start).Round(time.Millisecond))
		}
	}

	// Calculate cross-provider similarity if both embeddings are available
	if comparison.OpenAIEmbedding != nil && comparison.GeminiEmbedding != nil {
		// Since OpenAI (1536D) and Gemini (768D) have different dimensions,
		// we can't directly compare them. We'll note this limitation.
		if len(comparison.OpenAIEmbedding) == len(comparison.GeminiEmbedding) {
			comparison.CrossSimilarity = cosineSimilarity(comparison.OpenAIEmbedding, comparison.GeminiEmbedding)
		} else {
			comparison.CrossSimilarity = -1 // Indicates different dimensions
		}
	}

	return comparison, nil
}

// displayProviderComparison shows the provider comparison results
func displayProviderComparison(comp *ProviderComparison) {
	fmt.Printf("🔬 Provider Comparison Results:\n\n")

	// Provider availability
	fmt.Printf("📡 Provider Availability:\n")
	fmt.Printf("   OpenAI:  %s\n", getAvailabilityStatus(comp.OpenAIAvailable, comp.OpenAIEmbedding != nil))
	fmt.Printf("   Gemini:  %s\n\n", getAvailabilityStatus(comp.GeminiAvailable, comp.GeminiEmbedding != nil))

	// Embedding details
	if comp.OpenAIEmbedding != nil {
		fmt.Printf("🤖 OpenAI Embedding:\n")
		fmt.Printf("   Dimensions: %d\n", comp.Dimensions["openai"])
		fmt.Printf("   Status: %s\n", comp.GenerationTime["openai"])
		if comp.OpenAIGenerated {
			fmt.Printf("   Sample values: %.6f, %.6f, %.6f\n",
				comp.OpenAIEmbedding[0], comp.OpenAIEmbedding[1], comp.OpenAIEmbedding[2])
		}
		fmt.Println()
	} else if comp.OpenAIAvailable {
		fmt.Printf("❌ OpenAI Embedding: %s\n\n", comp.Errors["openai"])
	}

	if comp.GeminiEmbedding != nil {
		fmt.Printf("💎 Gemini Embedding:\n")
		fmt.Printf("   Dimensions: %d\n", comp.Dimensions["gemini"])
		fmt.Printf("   Status: %s\n", comp.GenerationTime["gemini"])
		if comp.GeminiGenerated {
			fmt.Printf("   Sample values: %.6f, %.6f, %.6f\n",
				comp.GeminiEmbedding[0], comp.GeminiEmbedding[1], comp.GeminiEmbedding[2])
		}
		fmt.Println()
	} else if comp.GeminiAvailable {
		fmt.Printf("❌ Gemini Embedding: %s\n\n", comp.Errors["gemini"])
	}

	// Cross-provider analysis
	if comp.OpenAIEmbedding != nil && comp.GeminiEmbedding != nil {
		fmt.Printf("🔗 Cross-Provider Analysis:\n")
		if comp.CrossSimilarity >= 0 {
			fmt.Printf("   Similarity: %.6f\n", comp.CrossSimilarity)
			fmt.Printf("   Interpretation: %s\n", interpretCrossSimilarity(comp.CrossSimilarity))
		} else {
			fmt.Printf("   Similarity: Cannot compute (different dimensions: %d vs %d)\n",
				comp.Dimensions["openai"], comp.Dimensions["gemini"])
			fmt.Printf("   Note: OpenAI uses 1536D vectors, Gemini uses 768D vectors\n")
		}
		fmt.Println()
	}

	// Recommendations
	fmt.Printf("💡 Recommendations:\n")
	if !comp.OpenAIAvailable && !comp.GeminiAvailable {
		fmt.Printf("   ⚠️  No API keys available - configure OPENAI_API_KEY or GEMINI_API_KEY\n")
	} else if comp.OpenAIEmbedding == nil && comp.GeminiEmbedding == nil {
		fmt.Printf("   ⚠️  No embeddings could be generated or retrieved\n")
	} else {
		if comp.OpenAIEmbedding != nil && comp.GeminiEmbedding != nil {
			fmt.Printf("   ✅ Both providers working - consider A/B testing for your use case\n")
			fmt.Printf("   💰 Cost: OpenAI typically more expensive, Gemini more cost-effective\n")
			fmt.Printf("   📊 Quality: Test both providers with your specific domain data\n")
		} else if comp.OpenAIEmbedding != nil {
			fmt.Printf("   ✅ OpenAI working - industry standard with proven performance\n")
		} else if comp.GeminiEmbedding != nil {
			fmt.Printf("   ✅ Gemini working - cost-effective alternative with good performance\n")
		}
	}
}

// getAvailabilityStatus returns a human-readable status for provider availability
func getAvailabilityStatus(apiAvailable, embeddingExists bool) string {
	if apiAvailable && embeddingExists {
		return "✅ Available & Working"
	} else if apiAvailable {
		return "🟡 API Key Available"
	} else {
		return "❌ No API Key"
	}
}

// interpretCrossSimilarity provides interpretation for cross-provider similarity
func interpretCrossSimilarity(similarity float64) string {
	switch {
	case similarity >= 0.8:
		return "High correlation - providers agree strongly"
	case similarity >= 0.6:
		return "Good correlation - providers generally agree"
	case similarity >= 0.4:
		return "Moderate correlation - some agreement"
	case similarity >= 0.2:
		return "Low correlation - providers differ significantly"
	default:
		return "Very low correlation - providers disagree substantially"
	}
}
